### ISSUE TITLE
Running 05_textured_cube on linux causes segfault

### ISSUE THREAD

**Issue by dacki** [d-gamedev-team/opengl-tutorials#6]
I've been trying to run the example no.5 on linux (lenovo x230 / hd4000 / arch-linux)
and get an glexception when reading a texture from file.

As you can see in the stacktrace glGenerateMipmap is the last function before diving into the drivers. When I change the example to set the bool for MipMap to false the program runs correctly.

There is also place in the code where the following is written:

>If mipmaps is true, the gl extensions must be loaded, otherwise bad things will happen!

I don't know exactly what is meant so maybe that will fix the problem?

------------------------------------

Program received signal SIGSEGV, Segmentation fault.
0x000000000055763c in _d_throwc ()
(gdb) bt
#0  0x000000000055763c in _d_throwc ()
#1  0x000000000050cabd in glErrorCallback (source=33350, type=33360, id=1, 
    severity=37191, length=40, 
    message=0x7fffffffbe30 "Recompiling vertex shader for program 6\n", 
    userParam=0x0) at ../../../../utility/src/gltut/window.d:194
#2  0x00007ffff26a6bf0 in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
#3  0x00007ffff29c3691 in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
#4  0x00007ffff29abef3 in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
#5  0x00007ffff29c31c6 in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
#6  0x00007ffff29c3a41 in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
#7  0x00007ffff29a6c90 in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
#8  0x00007ffff29476dc in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
#9  0x00007ffff279a84c in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
#10 0x00007ffff28282a4 in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
#11 0x00007ffff2708128 in ?? () from /usr/lib/xorg/modules/dri/i965_dri.so
#12 0x0000000000512dc4 in _D7glamour4util58__T7checkglS41_D4glad2gl5funcs16glGenerateMipmapPUNbkZvTkZ7checkglFkZv (_param_0=3553)
    at ../../../../../../.dub/packages/glamour-drey-0.0.3-alpha/src/glamour/util.d:56
#13 0x000000000051229e in _D7glamour7texture9Texture2D16__T8set_dataTPvZ8set_dataMFPviiikkbiZv (this=0x7ffff7ec4fc0, level=0, mipmaps=true, type=5121, 
    format=6407, height=512, width=512, internal_format=6407, 
    data=0x7ffff0ac7010)
---Type <return> to continue, or q <return> to quit---
    at ../../../../../../.dub/packages/glamour-drey-0.0.3-alpha/src/glamour/texture.d:267
#14 0x0000000000511ef2 in glamour.texture.Texture2D.from_image(immutable(char)[]) (filename=...)
    at ../../../../../../.dub/packages/glamour-drey-0.0.3-alpha/src/glamour/texture.d:340
#15 0x00000000004ee1e0 in tut_05_textured_cube.ProgramState.initTextures() (
    this=0x7ffff7ec0e08) at tut_05_textured_cube.d:156
#16 0x00000000004ed8a6 in tut_05_textured_cube.ProgramState.this(glwtf.window.Window) (this=0x7ffff7ec0e08, window=0x7ffff129a000) at tut_05_textured_cube.d:57
#17 0x00000000004eee2f in D main () at tut_05_textured_cube.d:466

**Comment by dacki** [comment]
I installed linux on my home computer with different hardware (ATI GPU instead of onboard) and the example runs so I think it was the issue was driver related.

I'll try to run all the examples to actually confirm that they aren't only building but properly running.

However dub currently prevents me from building the projects.

> Error executing command run:
>Could not find a valid dependency tree configuration:
>No match for dependency gl3n ~master of tut06  

Cheers

**Comment by AndrejMitrovic** [comment]
Ok cool, will update the dependencies.
